projects:
  Codegen Project:
    schemaPath: ../backend/video-call/schema.graphql
    includes: src/features/video-call/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/features/video-call/graphql-api.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/features/video-call/graphql-api.ts
        docsFilePath: src/features/video-call/graphql
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
