/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutAlertsImport } from './routes/_layout/alerts'
import { Route as LayoutAlertAlertIdImport } from './routes/_layout/alert.$alertId'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutAlertsRoute = LayoutAlertsImport.update({
  path: '/alerts',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAlertAlertIdRoute = LayoutAlertAlertIdImport.update({
  path: '/alert/$alertId',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/alerts': {
      id: '/_layout/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof LayoutAlertsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/alert/$alertId': {
      id: '/_layout/alert/$alertId'
      path: '/alert/$alertId'
      fullPath: '/alert/$alertId'
      preLoaderRoute: typeof LayoutAlertAlertIdImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LayoutRoute: LayoutRoute.addChildren({
    LayoutAlertsRoute,
    LayoutAlertAlertIdRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/alerts",
        "/_layout/alert/$alertId"
      ]
    },
    "/_layout/alerts": {
      "filePath": "_layout/alerts.tsx",
      "parent": "/_layout"
    },
    "/_layout/alert/$alertId": {
      "filePath": "_layout/alert.$alertId.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
