name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Build backend API
        working-directory: ./backend/api
        run: |
          npm ci
          npm run build

      - name: Build video call service
        working-directory: ./backend/video-call
        run: |
          npm ci
          npm run build

      - name: Build video summary generator
        working-directory: ./backend/video-summary-generator
        run: |
          npm ci
          npm run build

      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

  cdk-synth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Build all packages
        run: npm run build

      - name: Install CDK dependencies
        working-directory: ./cdk
        run: npm ci

      - name: CDK Synth
        working-directory: ./cdk
        run: npx cdk synth
